/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androidex_devices_aexddZT */

#ifndef _Included_com_androidex_devices_aexddZT
#define _Included_com_androidex_devices_aexddZT
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jint JNICALL aexddZT_JNI_OnLoad(JavaVM *vm, void *reserved);
JNIEXPORT void JNICALL aexddZT_JNI_OnUnload(JavaVM* vm, void* reserved);
/*
 * Class:     com_androidex_devices_aexddZT
 * Method:    ztOpen
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_devices_aexddZT_ztOpen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_androidex_devices_aexddZT
 * Method:    ztClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_androidex_devices_aexddZT_ztClose
  (JNIEnv *, jobject);

/*
 * Class:     com_androidex_devices_aexddZT
 * Method:    ztReset
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddZT_ztReset
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddZT
 * Method:    ztGetVersion
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_devices_aexddZT_ztGetVersion
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
