/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androidex_devices_aexddPasswordKeypad */

#ifndef _Included_com_androidex_devices_aexddPasswordKeypad
#define _Included_com_androidex_devices_aexddPasswordKeypad
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL aexddPasswordKeypad_JNI_OnLoad(JavaVM *vm, void *reserved);
JNIEXPORT void JNICALL aexddPasswordKeypad_JNI_OnUnload(JavaVM* vm, void* reserved);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyFind
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jstring JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyFind
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyOpen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jstring JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyOpen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyClose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyClose
  (JNIEnv *, jobject);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyReset
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyReset
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyResetWithPpin
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyResetWithPpin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyGetSn
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyGetSn
  (JNIEnv *, jobject, jint);
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmySetSn
  (JNIEnv *, jobject, jstring,jint);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyGetVersion
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyGetVersion
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmySetEncryptMode
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmySetEncryptMode
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyDlMasterKey
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyDlMasterKey
  (JNIEnv *, jobject, jint, jstring, jint);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyDlWorkKey
 * Signature: (IILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyDlWorkKey
  (JNIEnv *, jobject, jint, jint, jstring, jint);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyActiveWorkKey
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyActiveWorkKey
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyOpenKeypad
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyOpenKeypad
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyDlCardNo
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyDlCardNo
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyStartPin
 * Signature: (SSSSSI)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyStartPin
  (JNIEnv *, jobject, jshort, jshort, jshort, jshort, jshort, jint);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyPinBlock
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyPinBlock
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyReadPin
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyReadPin
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyEncrypt
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyEncrypt
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyDecrypt
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyDecrypt
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyCalcMacData
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyCalcMacData
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_androidex_devices_aexddPasswordKeypad
 * Method:    kmyStartReadKey
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_androidex_devices_aexddPasswordKeypad_kmyStartReadKey
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
