/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androidex_devices_aexddPoscReader */

#ifndef _Included_com_androidex_devices_aexddPoscReader
#define _Included_com_androidex_devices_aexddPoscReader
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL aexddPoscReader_JNI_OnLoad(JavaVM* vm, void* reserved);
void JNICALL aexddPoscReader_JNI_OnUnload(JavaVM* vm, void* reserved);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    Find
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_devices_aexddPoscReader_Find
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    Open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPoscReader_Open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_androidex_devices_aexddPoscReader_Close
  (JNIEnv *, jobject);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    Reset
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_devices_aexddPoscReader_Reset
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    ReadCard
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPoscReader_ReadCard
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    RFM_13_Ring
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPoscReader_RFM_113_1Ring
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    RFM_13_ReadGuid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPoscReader_RFM_113_1ReadGuid
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    RFM_13_ReadCard
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPoscReader_RFM_113_1ReadCard
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    RFM_13_WriteCard
 * Signature: (I[BI[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPoscReader_RFM_113_1WriteCard
  (JNIEnv *, jobject, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    MF_30_ReadCard
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPoscReader_MF_130_1ReadCard
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    MF_30_WriteCard
 * Signature: (II[BI)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPoscReader_MF_130_1WriteCard
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    MF_30_ReadGuid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPoscReader_MF_130_1ReadGuid
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    MF_30_GetVer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPoscReader_MF_130_1GetVer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    MF_30_ReadCardbyPwd
 * Signature: (II[BII)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPoscReader_MF_130_1ReadCardbyPwd
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    CPU_Reset
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPoscReader_CPU_1Reset
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    CPU_PowerOn
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPoscReader_CPU_1PowerOn
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    CPU_PowerOff
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPoscReader_CPU_1PowerOff
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    CPU_Apdu
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPoscReader_CPU_1Apdu
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    serial_read
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_androidex_devices_aexddPoscReader_serial_1read
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    serial_write
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPoscReader_serial_1write
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_androidex_devices_aexddPoscReader
 * Method:    serial_select
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddPoscReader_serial_1select
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
