/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androidex_devices_aexddMT318 */

#ifndef _Included_com_androidex_devices_aexddMT318
#define _Included_com_androidex_devices_aexddMT318
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL aexddMT318_JNI_OnLoad(JavaVM* vm, void* reserved);
void JNICALL aexddMT318_JNI_OnUnload(JavaVM* vm, void* reserved);

JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddMT318Reader_mt318ReadCardLoop
        (JNIEnv *, jobject, jint,jint);
JNIEXPORT void JNICALL Java_com_androidex_devices_aexddMT318Reader_mt318SendCmd
        (JNIEnv *, jobject, jint, jstring, jint);
JNIEXPORT void JNICALL Java_com_androidex_devices_aexddMT318Reader_mt318SendHexCmd
        (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
