/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androidex_devices_aexddMT318 */

#ifndef _Included_com_androidex_devices_aexddMT318
#define _Included_com_androidex_devices_aexddMT318
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL aexddMT318_JNI_OnLoad(JavaVM* vm, void* reserved);
void JNICALL aexddMT318_JNI_OnUnload(JavaVM* vm, void* reserved);

/*
 * Class:     com_androidex_devices_aexddMT318
 * Method:    Open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jstring JNICALL Java_com_androidex_devices_aexddMT318Reader_native_1mt318_1Open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_androidex_devices_aexddMT318
 * Method:    Close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_androidex_devices_aexddMT318Reader_native_1mt318_1Close
  (JNIEnv *, jobject);

/*
 * Class:     com_androidex_devices_aexddMT318
 * Method:    Reset
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidex_devices_aexddMT318Reader_native_1mt318_1Reset
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddMT318
 * Method:    ReadCard
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddMT318Reader_native_1mt318_1ReadCard
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_androidex_devices_aexddMT318
 * Method:    RFM_13_Ring
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddMT318Reader_native_1mt318_1RFM_113_1Ring
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddMT318
 * Method:    RFM_13_ReadGuid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddMT318Reader_native_1mt318_1RFM_113_1ReadGuid
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddMT318
 * Method:    RFM_13_ReadCard
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddMT318Reader_native_1mt318_1RFM_113_1ReadCard
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_androidex_devices_aexddMT318
 * Method:    RFM_13_WriteCard
 * Signature: (I[BI[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddMT318Reader_native_1mt318_1RFM_113_1WriteCard
  (JNIEnv *, jobject, jint, jbyteArray, jint, jbyteArray, jint, jbyteArray, jint);

/*
 * Class:     com_androidex_devices_aexddMT318
 * Method:    MF_30_ReadCard
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddMT318Reader_native_1mt318_1MF_130_1ReadCard
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_androidex_devices_aexddMT318
 * Method:    MF_30_WriteCard
 * Signature: (II[BI)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddMT318Reader_native_1mt318_1MF_130_1WriteCard
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint);

/*
 * Class:     com_androidex_devices_aexddMT318
 * Method:    MF_30_ReadGuid
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddMT318Reader_native_1mt318_1MF_130_1ReadGuid
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddMT318
 * Method:    MF_30_GetVer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddMT318Reader_native_1mt318_1MF_130_1GetVer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddMT318
 * Method:    MF_30_ReadCardbyPwd
 * Signature: (II[BII)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddMT318Reader_native_1mt318_1MF_130_1ReadCardbyPwd
  (JNIEnv *, jobject, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_androidex_devices_aexddMT318
 * Method:    CPU_Reset
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddMT318Reader_native_1mt318_1CPU_1Reset
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddMT318
 * Method:    CPU_PowerOn
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddMT318Reader_native_1mt318_1CPU_1PowerOn
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddMT318
 * Method:    CPU_PowerOff
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddMT318Reader_native_1mt318_1CPU_1PowerOff
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddMT318
 * Method:    CPU_Apdu
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddMT318Reader_native_1mt318_1CPU_1Apdu
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
