/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androidex_devices_aexddB58Printer */

#ifndef _Included_com_androidex_devices_aexddB58Printer
#define _Included_com_androidex_devices_aexddB58Printer
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL aexddB58T_JNI_OnLoad(JavaVM* vm, void* reserved);
JNIEXPORT void JNICALL aexddB58T_JNI_OnUnload(JavaVM* vm, void* reserved);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jstring JNICALL Java_com_androidex_devices_aexddB58Printer_native_1open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_native_1close
  (JNIEnv *, jobject);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    newline
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_newline
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    set_fontsize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_set_1fontsize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    set_linewide
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_set_1linewide
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    initialize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_initialize
  (JNIEnv *, jobject);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    set_charDSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_set_1charDSize
  (JNIEnv *, jobject);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    set_charNSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_set_1charNSize
  (JNIEnv *, jobject);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    set_graph
 * Signature: (CCCLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_set_1graph
  (JNIEnv *, jobject, jchar, jchar, jchar, jstring);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    set_barcodeHigh
 * Signature: (C)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_set_1barcodeHigh
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    set_barcodeWide
 * Signature: (C)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_set_1barcodeWide
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    out_barcode
 * Signature: (CCCLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_out_1barcode
  (JNIEnv *, jobject, jchar, jchar, jchar, jstring, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    cmdline
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_cmdline
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    out_2Dimensional
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_out_12Dimensional
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    cut
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_cut
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    stepline
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_stepline
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    set_charwide
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_set_1charwide
  (JNIEnv *, jobject);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    getstatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_getstatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    getfactory
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_getfactory
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    set_align
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_set_1align
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    WHE25_getstatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_WHE25_1getstatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    SGT801_out_2Dimensional
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_SGT801_1out_12Dimensional
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    T_500AP_out_barcode
 * Signature: (CCCLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_T_1500AP_1out_1barcode
  (JNIEnv *, jobject, jchar, jchar, jchar, jstring, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    T_500AP_out_2Dimensional
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_T_1500AP_1out_12Dimensional
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    RG_CB532_out_barcode
 * Signature: (CCCLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_RG_1CB532_1out_1barcode
  (JNIEnv *, jobject, jchar, jchar, jchar, jstring, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    RG_CB532_out_2Dimensional
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_RG_1CB532_1out_12Dimensional
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    TA_500_out_2Dimensional
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_TA_1500_1out_12Dimensional
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    TA_500_cut
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_TA_1500_1cut
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_androidex_devices_aexddB58Printer
 * Method:    out_bitmap
 * Signature: ([BIIIII)I
 */
JNIEXPORT jint JNICALL Java_com_androidex_devices_aexddB58Printer_out_1bitmap
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
